version: 2

build:
  image: latest

conda:
  environment: environment.yml

python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all

formats: []
